language: haskell
sudo: false
branches:
  only:
  - master
install:
  - pip install --user ghp-import
script:
  - git clone --branch=hakyll-bin https://github.com/pep-dortmund/toolbox.pep-dortmund.de repo-bin
  - xz -cdf repo-bin/site.xz > site
  - chmod +x site
  - ./site build
after_success:
  - openssl aes-256-cbc -K $encrypted_6a537145ae27_key -iv $encrypted_6a537145ae27_iv -in .travis/github_deploy_key.enc -out ~/.ssh/id_rsa -d
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && sh publish.sh > /dev/null 2>&1 || true'
notifications:
  email: false
env:
  global:
    secure: H4cVmx8HVfDRoS69Y5SxM7uCWPfB8Wz+/7Pxtn/08OzYtJJGFd+K+Dd43Y8G+MHwK221dLXNd8TOzpZCF3UyaWDaXFpGb8j4hF6gSxIyC2WVSl6/LMyJm9yT+lW0vFYM0/GVrJ9Xolxk3HZ/Mbr8PGs85FvxQL6U0SF2wL6+6Sw=
